-- FitConnect Database Seed Data
-- Run this in Supabase SQL Editor to populate all tables with mock data
-- This will insert: 10 studios, 10 instructors, and 36 classes

-- Insert Studios
INSERT INTO public.studios (name, description, location, phone, email, image_url, type, rating, review_count, amenities, is_active) VALUES
('ZenFlow Yoga Studio', 'A serene space dedicated to traditional and modern yoga practices. Our experienced instructors guide you through mindful movement and breath work.', '2847 N. Clark Street, Chicago, IL 60657', '(312) 555-0198', 'hello@zenflowstudio.com', 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800', ARRAY['Yoga'], 4.8, 124, ARRAY['Showers', 'Lockers', 'Mat Rental', 'Parking', 'Changing Rooms'], true),
('PowerCycle Studio', 'High-energy indoor cycling classes with motivating instructors and premium bikes. Ride to the beat and transform your fitness.', '1523 W. Fullerton Ave, Chicago, IL 60614', '(312) 555-0167', 'ride@powercycle.com', 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800', ARRAY['Cycling'], 4.9, 289, ARRAY['Showers', 'Lockers', 'Shoe Rental', 'Towel Service', 'Smoothie Bar'], true),
('CoreStrength Pilates', 'Classical and contemporary Pilates on reformers and mats. Small class sizes ensure personalized attention and proper form.', '890 W. Armitage Ave, Chicago, IL 60614', '(312) 555-0143', 'info@corestrength.com', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800', ARRAY['Pilates'], 4.7, 98, ARRAY['Equipment Provided', 'Lockers', 'Private Sessions Available'], true),
('Urban Boxing Club', 'Technical boxing training meets high-intensity cardio. Learn proper technique while getting an incredible workout.', '3421 N. Southport Ave, Chicago, IL 60657', '(312) 555-0189', 'fight@urbanboxing.com', 'https://images.unsplash.com/photo-1517438476312-10d79c077509?w=800', ARRAY['Boxing'], 4.6, 156, ARRAY['Gloves Rental', 'Showers', 'Lockers', 'Heavy Bags', 'Speed Bags'], true),
('Rhythm Dance Collective', 'Contemporary, hip-hop, and jazz dance classes for all levels. Express yourself through movement in a supportive environment.', '1678 N. Milwaukee Ave, Chicago, IL 60647', '(312) 555-0176', 'dance@rhythmcollective.com', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800', ARRAY['Dance'], 4.9, 203, ARRAY['Sprung Floors', 'Sound System', 'Mirrors', 'Water Fountain'], true),
('HIIT Factory', 'Intense, results-driven HIIT workouts that maximize calorie burn in minimal time. No two classes are ever the same.', '2156 W. Division Street, Chicago, IL 60622', '(312) 555-0192', 'hello@hiitfactory.com', 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800', ARRAY['HIIT'], 4.7, 187, ARRAY['Showers', 'Towel Service', 'Heart Rate Monitors', 'Parking'], true),
('Serenity Barre Studio', 'Ballet-inspired barre workouts that sculpt and tone. Low-impact, high-intensity classes suitable for all fitness levels.', '945 W. Armitage Ave, Chicago, IL 60614', '(312) 555-0134', 'info@serenitybarre.com', 'https://images.unsplash.com/photo-1518310952931-b1de897abd40?w=800', ARRAY['Barre'], 4.8, 142, ARRAY['Grippy Socks Required', 'Lockers', 'Retail Boutique', 'Childcare'], true),
('FlowState Yoga & Meditation', 'Traditional yoga practices combined with guided meditation. Find your flow and inner peace in our tranquil studio.', '3782 N. Southport Ave, Chicago, IL 60613', '(312) 555-0156', 'om@flowstateyoga.com', 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800', ARRAY['Yoga'], 4.9, 167, ARRAY['Meditation Room', 'Tea Bar', 'Mat Rental', 'Props Provided'], true),
('Martial Arts Academy', 'Traditional martial arts training including Karate, Taekwondo, and Jiu-Jitsu. Build discipline, confidence, and self-defense skills.', '2234 W. Belmont Ave, Chicago, IL 60618', '(312) 555-0178', 'train@maacademy.com', 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800', ARRAY['Martial Arts'], 4.7, 134, ARRAY['Equipment Provided', 'Changing Rooms', 'Belt Testing', 'Kids Classes'], true),
('The Strength Lab', 'Evidence-based strength training in a supportive group setting. Build muscle, increase metabolism, and feel empowered.', '1567 N. Damen Ave, Chicago, IL 60622', '(312) 555-0145', 'lift@strengthlab.com', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800', ARRAY['Strength Training'], 4.8, 201, ARRAY['Olympic Platforms', 'Free Weights', 'Showers', 'Nutrition Coaching'], true);

-- Insert Instructors (using subqueries to get studio_id by studio name)
INSERT INTO public.instructors (studio_id, name, bio, profile_image_url, specialties, certifications, years_experience, rating, is_active)
SELECT
  (SELECT id FROM public.studios WHERE name = 'ZenFlow Yoga Studio'),
  'Sarah Mitchell',
  'Sarah has been practicing yoga for 15 years and teaching for 8. She believes in making yoga accessible to everyone, regardless of experience level.',
  'https://randomuser.me/api/portraits/women/1.jpg',
  ARRAY['Vinyasa Flow', 'Yin Yoga', 'Meditation'],
  ARRAY['RYT-500', 'Meditation Teacher Training'],
  8,
  4.9,
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'PowerCycle Studio'),
  'Marcus Johnson',
  'Former competitive cyclist turned indoor cycling instructor. Marcus brings high energy and motivating playlists to every ride.',
  'https://randomuser.me/api/portraits/men/2.jpg',
  ARRAY['Spin', 'HIIT Cycling', 'Endurance'],
  ARRAY['Spinning Certified', 'CPR/AED'],
  6,
  4.8,
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'CoreStrength Pilates'),
  'Elena Rodriguez',
  'Classically trained in the authentic Pilates method, Elena focuses on precision and control to help clients build functional strength.',
  'https://randomuser.me/api/portraits/women/3.jpg',
  ARRAY['Classical Pilates', 'Reformer', 'Prenatal'],
  ARRAY['PMA Certified', 'Prenatal Pilates Specialist'],
  10,
  4.9,
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Urban Boxing Club'),
  'Troy Williams',
  'Amateur boxing champion with a passion for teaching proper form. Troy makes boxing accessible while keeping the intensity high.',
  'https://randomuser.me/api/portraits/men/4.jpg',
  ARRAY['Boxing Technique', 'Cardio Boxing', 'Personal Training'],
  ARRAY['USA Boxing Coach', 'NASM CPT'],
  12,
  4.7,
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Rhythm Dance Collective'),
  'Jasmine Lee',
  'Professional dancer and choreographer who has worked with touring artists. Jasmine creates fun, energetic classes that feel like a party.',
  'https://randomuser.me/api/portraits/women/5.jpg',
  ARRAY['Hip Hop', 'Contemporary', 'Choreography'],
  ARRAY['Dance Teacher Certification', 'ACE Group Fitness'],
  7,
  5.0,
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'HIIT Factory'),
  'Derek Thompson',
  'Former college athlete specializing in high-intensity interval training. Derek pushes you to your limits while keeping classes safe and effective.',
  'https://randomuser.me/api/portraits/men/6.jpg',
  ARRAY['HIIT', 'Bootcamp', 'Athletic Conditioning'],
  ARRAY['NASM CPT', 'TRX Certified', 'CrossFit Level 1'],
  5,
  4.8,
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Serenity Barre Studio'),
  'Amanda Foster',
  'Former professional ballet dancer bringing authentic technique to barre fitness. Amanda''s classes are challenging yet graceful.',
  'https://randomuser.me/api/portraits/women/7.jpg',
  ARRAY['Barre', 'Ballet Fitness', 'Stretching'],
  ARRAY['Barre Above Certified', 'Ballet Teacher Diploma'],
  9,
  4.9,
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'FlowState Yoga & Meditation'),
  'Michael Chen',
  'Studied yoga in India for two years and brings authentic teachings to modern practice. Michael specializes in the mental and spiritual aspects of yoga.',
  'https://randomuser.me/api/portraits/men/8.jpg',
  ARRAY['Hatha Yoga', 'Meditation', 'Breathwork'],
  ARRAY['E-RYT 500', 'Meditation Teacher', 'Reiki Master'],
  11,
  5.0,
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Martial Arts Academy'),
  'Sensei Robert Kim',
  '4th degree black belt with 20 years of martial arts experience. Sensei Kim emphasizes discipline, respect, and practical self-defense.',
  'https://randomuser.me/api/portraits/men/9.jpg',
  ARRAY['Karate', 'Self-Defense', 'Youth Training'],
  ARRAY['4th Dan Black Belt', 'Youth Fitness Specialist'],
  20,
  4.8,
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'The Strength Lab'),
  'Nicole Anderson',
  'Competitive powerlifter and certified strength coach. Nicole teaches proper lifting technique and helps clients build real-world strength.',
  'https://randomuser.me/api/portraits/women/10.jpg',
  ARRAY['Strength Training', 'Olympic Lifting', 'Powerlifting'],
  ARRAY['CSCS', 'USAW Level 1', 'Precision Nutrition Level 1'],
  8,
  4.9,
  true;

-- Insert Classes (using subqueries to get studio_id and instructor_id by names)
INSERT INTO public.classes (studio_id, instructor_id, name, description, type, difficulty, duration, date, time, price, current_capacity, max_capacity, image_url, is_active)
SELECT
  (SELECT id FROM public.studios WHERE name = 'ZenFlow Yoga Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Sarah Mitchell'),
  'Morning Vinyasa Flow',
  'Start your day with an energizing vinyasa flow. Connect breath with movement in this dynamic practice.',
  'Yoga',
  'Intermediate',
  60,
  '2025-11-20'::date,
  '07:00'::time,
  22,
  8,
  15,
  'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'ZenFlow Yoga Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Sarah Mitchell'),
  'Gentle Yin Yoga',
  'Slow-paced class focusing on deep stretches held for several minutes. Perfect for stress relief and flexibility.',
  'Yoga',
  'Beginner',
  75,
  '2025-11-20'::date,
  '18:30'::time,
  24,
  12,
  15,
  'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'ZenFlow Yoga Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Sarah Mitchell'),
  'Power Yoga',
  'Vigorous, fitness-based approach to vinyasa-style yoga. Build strength and stamina while improving flexibility.',
  'Yoga',
  'Advanced',
  60,
  '2025-11-21'::date,
  '06:00'::time,
  25,
  14,
  15,
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'PowerCycle Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Marcus Johnson'),
  'Sunrise Ride',
  'High-energy cycling class with hills, sprints, and intervals. Ride to the beat of motivating music.',
  'Cycling',
  'Intermediate',
  45,
  '2025-11-20'::date,
  '06:00'::time,
  28,
  18,
  20,
  'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'PowerCycle Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Marcus Johnson'),
  'Rhythm Ride',
  'Choreographed cycling experience where every move is synced to the music. Fun, effective, and addictive.',
  'Cycling',
  'Beginner',
  45,
  '2025-11-20'::date,
  '18:00'::time,
  28,
  15,
  20,
  'https://images.unsplash.com/photo-1485727749690-d091f284fe6d?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'PowerCycle Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Marcus Johnson'),
  'Power Hour',
  'Extended ride for serious cyclists. Endurance training with challenging climbs and speed work.',
  'Cycling',
  'Advanced',
  60,
  '2025-11-21'::date,
  '12:00'::time,
  32,
  20,
  20,
  'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'CoreStrength Pilates'),
  (SELECT id FROM public.instructors WHERE name = 'Elena Rodriguez'),
  'Reformer Basics',
  'Introduction to reformer Pilates. Learn proper form and fundamental exercises on the reformer.',
  'Pilates',
  'Beginner',
  55,
  '2025-11-20'::date,
  '09:00'::time,
  35,
  5,
  8,
  'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'CoreStrength Pilates'),
  (SELECT id FROM public.instructors WHERE name = 'Elena Rodriguez'),
  'Advanced Reformer',
  'Challenging reformer class for experienced practitioners. Complex exercises requiring strength and control.',
  'Pilates',
  'Advanced',
  55,
  '2025-11-20'::date,
  '17:00'::time,
  38,
  7,
  8,
  'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'CoreStrength Pilates'),
  (SELECT id FROM public.instructors WHERE name = 'Elena Rodriguez'),
  'Mat Pilates',
  'Classical mat work focusing on core strength, stability, and flexibility. No equipment needed.',
  'Pilates',
  'Intermediate',
  50,
  '2025-11-21'::date,
  '18:00'::time,
  26,
  10,
  12,
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Urban Boxing Club'),
  (SELECT id FROM public.instructors WHERE name = 'Troy Williams'),
  'Boxing Fundamentals',
  'Learn proper boxing technique including stance, footwork, and basic punches. Great workout with skill development.',
  'Boxing',
  'Beginner',
  60,
  '2025-11-20'::date,
  '18:00'::time,
  26,
  12,
  16,
  'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Urban Boxing Club'),
  (SELECT id FROM public.instructors WHERE name = 'Troy Williams'),
  'Cardio Boxing',
  'High-intensity boxing workout focused on cardio and calorie burn. Combination drills and conditioning.',
  'Boxing',
  'Intermediate',
  45,
  '2025-11-21'::date,
  '06:30'::time,
  24,
  14,
  16,
  'https://images.unsplash.com/photo-1517438476312-10d79c077509?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Urban Boxing Club'),
  (SELECT id FROM public.instructors WHERE name = 'Troy Williams'),
  'Heavy Bag Training',
  'Intensive heavy bag work with advanced combinations. Develop power, speed, and endurance.',
  'Boxing',
  'Advanced',
  60,
  '2025-11-22'::date,
  '19:00'::time,
  28,
  10,
  12,
  'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Rhythm Dance Collective'),
  (SELECT id FROM public.instructors WHERE name = 'Jasmine Lee'),
  'Hip Hop Basics',
  'Learn foundational hip hop moves and grooves. No experience necessary, just bring your energy.',
  'Dance',
  'Beginner',
  60,
  '2025-11-20'::date,
  '19:00'::time,
  20,
  16,
  25,
  'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Rhythm Dance Collective'),
  (SELECT id FROM public.instructors WHERE name = 'Jasmine Lee'),
  'Contemporary Flow',
  'Fluid contemporary dance exploring movement quality and expression. Previous dance experience recommended.',
  'Dance',
  'Intermediate',
  75,
  '2025-11-21'::date,
  '18:00'::time,
  22,
  18,
  25,
  'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Rhythm Dance Collective'),
  (SELECT id FROM public.instructors WHERE name = 'Jasmine Lee'),
  'Cardio Dance Party',
  'Fun, high-energy dance workout mixing different styles. More about having fun than perfect choreography.',
  'Dance',
  'Beginner',
  45,
  '2025-11-22'::date,
  '10:00'::time,
  18,
  22,
  30,
  'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'HIIT Factory'),
  (SELECT id FROM public.instructors WHERE name = 'Derek Thompson'),
  'Morning Meltdown',
  'Start your day with intense intervals combining cardio and strength. Maximum calorie burn in minimal time.',
  'HIIT',
  'Intermediate',
  45,
  '2025-11-20'::date,
  '06:00'::time,
  25,
  18,
  24,
  'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'HIIT Factory'),
  (SELECT id FROM public.instructors WHERE name = 'Derek Thompson'),
  'Tabata Blast',
  'Pure Tabata protocol: 20 seconds max effort, 10 seconds rest. Short but incredibly effective.',
  'HIIT',
  'Advanced',
  30,
  '2025-11-20'::date,
  '12:00'::time,
  22,
  15,
  20,
  'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'HIIT Factory'),
  (SELECT id FROM public.instructors WHERE name = 'Derek Thompson'),
  'Bootcamp HIIT',
  'Military-style bootcamp with HIIT intervals. Modifications available for all fitness levels.',
  'HIIT',
  'Beginner',
  50,
  '2025-11-21'::date,
  '18:30'::time,
  24,
  20,
  24,
  'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Serenity Barre Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Amanda Foster'),
  'Classic Barre',
  'Traditional barre class using small, controlled movements. Sculpt and tone muscles with ballet-inspired exercises.',
  'Barre',
  'Beginner',
  55,
  '2025-11-20'::date,
  '09:00'::time,
  26,
  10,
  15,
  'https://images.unsplash.com/photo-1518310952931-b1de897abd40?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Serenity Barre Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Amanda Foster'),
  'Barre Cardio',
  'Faster-paced barre with cardio intervals. Get your heart rate up while sculpting lean muscle.',
  'Barre',
  'Intermediate',
  45,
  '2025-11-20'::date,
  '17:30'::time,
  24,
  13,
  15,
  'https://images.unsplash.com/photo-1518611507436-f9221403cca2?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'FlowState Yoga & Meditation'),
  (SELECT id FROM public.instructors WHERE name = 'Michael Chen'),
  'Meditation & Mindfulness',
  'Guided meditation practice to reduce stress and increase awareness. Suitable for complete beginners.',
  'Meditation',
  'Beginner',
  45,
  '2025-11-20'::date,
  '07:00'::time,
  18,
  8,
  20,
  'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'FlowState Yoga & Meditation'),
  (SELECT id FROM public.instructors WHERE name = 'Michael Chen'),
  'Breathwork Session',
  'Deep dive into pranayama breathing techniques. Harness the power of breath for energy and calm.',
  'Yoga',
  'Beginner',
  60,
  '2025-11-21'::date,
  '18:00'::time,
  20,
  12,
  20,
  'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Martial Arts Academy'),
  (SELECT id FROM public.instructors WHERE name = 'Sensei Robert Kim'),
  'Karate Fundamentals',
  'Traditional Karate training focusing on basic techniques, kata, and discipline. Great for beginners.',
  'Martial Arts',
  'Beginner',
  60,
  '2025-11-20'::date,
  '18:00'::time,
  30,
  10,
  20,
  'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Martial Arts Academy'),
  (SELECT id FROM public.instructors WHERE name = 'Sensei Robert Kim'),
  'Advanced Sparring',
  'Controlled sparring for experienced martial artists. Apply techniques in realistic scenarios.',
  'Martial Arts',
  'Advanced',
  90,
  '2025-11-21'::date,
  '19:00'::time,
  35,
  8,
  12,
  'https://images.unsplash.com/photo-1595435742656-5272d0cf4e3c?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'The Strength Lab'),
  (SELECT id FROM public.instructors WHERE name = 'Nicole Anderson'),
  'Strength Foundations',
  'Learn proper form for fundamental lifts: squat, deadlift, bench press, and overhead press.',
  'Strength Training',
  'Beginner',
  60,
  '2025-11-20'::date,
  '18:00'::time,
  32,
  8,
  12,
  'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'The Strength Lab'),
  (SELECT id FROM public.instructors WHERE name = 'Nicole Anderson'),
  'Olympic Lifting',
  'Technical Olympic weightlifting: snatch and clean & jerk. Previous lifting experience required.',
  'Strength Training',
  'Advanced',
  75,
  '2025-11-21'::date,
  '06:00'::time,
  38,
  6,
  8,
  'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'ZenFlow Yoga Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Sarah Mitchell'),
  'Restorative Yoga',
  'Deeply relaxing yoga using props to support the body. Perfect for recovery and stress relief.',
  'Yoga',
  'Beginner',
  75,
  '2025-11-22'::date,
  '10:00'::time,
  24,
  6,
  12,
  'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'PowerCycle Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Marcus Johnson'),
  'Climb & Grind',
  'Simulated hill climbs with heavy resistance. Build power and mental toughness.',
  'Cycling',
  'Advanced',
  50,
  '2025-11-22'::date,
  '08:00'::time,
  30,
  17,
  20,
  'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'CoreStrength Pilates'),
  (SELECT id FROM public.instructors WHERE name = 'Elena Rodriguez'),
  'Prenatal Pilates',
  'Safe, effective Pilates modified for pregnancy. Focus on core strength and pelvic floor health.',
  'Pilates',
  'Beginner',
  50,
  '2025-11-22'::date,
  '10:00'::time,
  36,
  4,
  6,
  'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Urban Boxing Club'),
  (SELECT id FROM public.instructors WHERE name = 'Troy Williams'),
  'Boxing for Fitness',
  'Boxing-inspired cardio workout. No sparring, just a great full-body workout.',
  'Boxing',
  'Beginner',
  45,
  '2025-11-22'::date,
  '12:00'::time,
  24,
  11,
  16,
  'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Rhythm Dance Collective'),
  (SELECT id FROM public.instructors WHERE name = 'Jasmine Lee'),
  'Jazz Technique',
  'Classic jazz dance technique with across-the-floor progressions and center combinations.',
  'Dance',
  'Intermediate',
  60,
  '2025-11-22'::date,
  '14:00'::time,
  22,
  14,
  20,
  'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'HIIT Factory'),
  (SELECT id FROM public.instructors WHERE name = 'Derek Thompson'),
  'Core Crusher',
  'Targeted core workout with HIIT principles. Strengthen and define your midsection.',
  'HIIT',
  'Intermediate',
  30,
  '2025-11-22'::date,
  '17:00'::time,
  20,
  16,
  20,
  'https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Serenity Barre Studio'),
  (SELECT id FROM public.instructors WHERE name = 'Amanda Foster'),
  'Stretch & Restore',
  'Gentle stretching combined with barre work. Focus on flexibility and recovery.',
  'Barre',
  'Beginner',
  45,
  '2025-11-22'::date,
  '11:00'::time,
  22,
  8,
  12,
  'https://images.unsplash.com/photo-1518310952931-b1de897abd40?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'FlowState Yoga & Meditation'),
  (SELECT id FROM public.instructors WHERE name = 'Michael Chen'),
  'Sunset Yoga',
  'Gentle evening yoga to unwind from the day. Slow flows and relaxation.',
  'Yoga',
  'Beginner',
  60,
  '2025-11-22'::date,
  '19:00'::time,
  20,
  14,
  20,
  'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'Martial Arts Academy'),
  (SELECT id FROM public.instructors WHERE name = 'Sensei Robert Kim'),
  'Self-Defense Workshop',
  'Practical self-defense techniques for real-world situations. Empowering and informative.',
  'Martial Arts',
  'Beginner',
  90,
  '2025-11-23'::date,
  '14:00'::time,
  35,
  12,
  15,
  'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=600',
  true
UNION ALL SELECT
  (SELECT id FROM public.studios WHERE name = 'The Strength Lab'),
  (SELECT id FROM public.instructors WHERE name = 'Nicole Anderson'),
  'Powerlifting Basics',
  'Introduction to competitive powerlifting. Learn the big three lifts with proper form.',
  'Strength Training',
  'Intermediate',
  90,
  '2025-11-23'::date,
  '10:00'::time,
  35,
  7,
  10,
  'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
  true;

-- Verify the inserted data
SELECT 'Studios inserted:' as info, COUNT(*) as count FROM public.studios
UNION ALL
SELECT 'Instructors inserted:', COUNT(*) FROM public.instructors
UNION ALL
SELECT 'Classes inserted:', COUNT(*) FROM public.classes;
